name = "nanoprobo"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "nanoprobo"

[[env.production.routes]]
pattern = "nanoprobo.com/*"
zone_name = "nanoprobo.com"

[[env.production.routes]]
pattern = "www.nanoprobo.com/*"
zone_name = "nanoprobo.com"

[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://nanoprobo.com"
